Fixed some grammatical issues, comments and code segments
SeleniumHQ/docs pull request #127
Opened 2017-04-30 03:19 UTC by User253489

Fixed some grammatical issues, comments and code segments

2017-05-23 12:59 UTC, andreastt requested changes
Sorry for the late review.

Please make the necessary changes I have highlighted. I would also have appreciated if you made one commit per file changed, but it’s fine to remember this for future PRs.

Please also keep the first line of your commit messages around 50 characters and use imperative language.

2017-05-23 12:59 UTC, andreastt commented on best.html
> + dealing with browsers (especially with cross-browser incompatibilities)
Keep dashes, alternatively use commas.

The dashes are currently used to highlight that this is an important fact, and placing it in parenthesis makes for the opposite effect.

2017-05-23 12:59 UTC, andreastt commented on best.html
> +tests themselves don’t need to change; only the code within the page
Keep comma. A semicolon should be used when listing multiple statements that each contain a comma, and is superfluous in this context.

2017-05-23 12:59 UTC, andreastt commented on index.html
> + <li><a href=remote.html#remote_webdriver>RemoteWebDriver</a>
This does not describe the `RemoteWebDriver` interfaces, but the concept of a _remote WebDriver_.

2017-05-23 12:59 UTC, andreastt commented on java.html
> +<p>You will occasionally want to validate the colour of something as part of your tests;
Drop use of semicolon.

2017-05-23 12:59 UTC, andreastt commented on remote.html
> +<title>RemoteWebDriver</title>
Keep old title.

2017-05-23 12:59 UTC, andreastt commented on remote.html
> +<h1>RemoteWebDriver</h1>
Revert.

2017-05-23 12:59 UTC, andreastt commented on remote.html
> +You can use RemoteWebDriver the same way you would use WebDriver
This should in fact say:

> You can use WebDriver remotely, …

2017-06-08 23:14 UTC, andreastt approved these changes

2017-06-09 00:09 UTC, User253489 commented
Thanks for the review.

I've made some but not all of the changes you highlighted. The ones I didn't make are such that our viewpoints on them differ but you can now make them if you want.

From now on, I'll (1) perform one commit per modified file, and (2) write my commit messages in the manner you requested.

2017-06-09 08:47 UTC, andreastt commented
@User253489 As you see, this does not apply to master because changes have been done in the interim. Do you want to have a shot at rebasing it?

2017-07-02 13:13 UTC, merged

2017-07-03 19:54 UTC, User253489 commented
Thanks for merging the changes after I rebased.