Update on_test_automation.es.md
SeleniumHQ/docs pull request #311
Opened 2019-08-11 17:00 UTC by AlexAndradeSan

Translate to Spanish.

I agreed the CLA

2019-08-11 20:37 UTC, diemol requested changes

2019-08-11 20:37 UTC, diemol commented on docs_source_files/content/introduction/on_test_automation.es.md
>  {{% notice info %}}
@AlexAndradeSan could you please remove the “notice”?
The page has been fully translated, so it’s not needed anymore

2019-08-11 22:10 UTC, AlexAndradeNet reviewed
I've resolve the notice in translation file

2019-08-12 11:22 UTC, diemol approved these changes
Thank you @AlexAndradeSan!

2019-08-12 11:22 UTC, merged