Understanding the components page translated
SeleniumHQ/docs pull request #353
Opened 2019-08-24 13:04 UTC by jesanmar1

The understanding the components page has been translated into Spanish

2019-08-24 19:49 UTC, diemol requested changes

2019-08-24 19:49 UTC, diemol commented on docs_source_files/content/webdriver/understanding_the_components.es.md
> -Building a test suite using WebDriver will require you to understand and
@jesanmar1 this part is missing in the Spanish translation

2019-08-25 09:24 UTC, jesanmar1 commented
Done @diemol !

2019-08-25 17:57 UTC, diemol approved these changes
Thank you @jesanmar1!

2019-08-25 17:58 UTC, merged