Added instructions for adding executables to your PATH
SeleniumHQ/docs pull request #98
Opened 2016-12-10 22:10 UTC by hazmeister

2016-12-10 22:48 UTC, andreastt requested changes
Please also format so that no lines have more than ~72 characters per line.

2016-12-10 22:48 UTC, andreastt commented on wd.html
> +</ul>
Use `<pre>`.

Also this only works when using the bash shell.

2016-12-10 22:48 UTC, andreastt commented on wd.html
> +    <li>Open a new cmd window as administrator and the run the following command to permanently add the directory to your path for all users on your machine:<pre><code>setx /m path "%path%;C:\WebDriv
s/cmd window/command prompt/

Also drop the `<code>`.

2016-12-10 22:48 UTC, andreastt commented on wd.html
> +    <li>Close all cmd windows and open a new one.  You can test by trying to run one of the binaries - e.g: <pre><code>chromedriver -v</code></pre>If that worked, you should be all set!</li>
* Again, s/cmd windows/command prompts/.
* Drop `<code>`.
* The last sentence doesn’t make sense. Please fix grammar.

2016-12-10 22:48 UTC, andreastt commented on wd.html
> +<p>By adding a folder containing WebDriver's binaries to your system's path, Selenium will be able to locate the additional binaries without requiring your test code to locate the exact location of t
Double full stop.

2016-12-11 07:50 UTC, hazmeister commented on wd.html
> +</ul>
Is there a better option we could recommend which works for all shells?  Or could I get away with spelling out this way only works with bash?

2016-12-11 08:54 UTC, hazmeister commented
Cheers for the review @andreastt - I've made some changes as requested.

2016-12-12 00:23 UTC, merged

2016-12-12 00:23 UTC, andreastt commented
Thanks!